package com.fit2081.Nadeem_Shayan_34075836.nutritrack.data.Patient
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a patient entity in the database.
 *
 * This data class is annotated with `@Entity` to
 * indicate that it represents a table in the database.
 * The `tableName` property specifies the name
 * of the table as "patients".
 */
@Entity(tableName = "Patient")
data class Patient(
    /**
     * The unique identifier for the patient.
     * It is automatically generated by the database.
     */
    @PrimaryKey
    val userId: Int = 0,

    val phoneNumber: Long,
    val name: String,
    val sex: String,
    val password: String,

    // HEIFA scores
    var heifaTotalScoreMale: Float?,
    var heifaTotalScoreFemale: Float?,
    var discretionaryHeifaScoreMale: Float?,
    var discretionaryHeifaScoreFemale: Float?,

    // Serving sizes
    var discretionaryServeSize: Float?,

    // Vegetables
    var vegetablesHeifaScoreMale: Float?,
    var vegetablesHeifaScoreFemale: Float?,
    var vegetablesWithLegumesAllocatedServeSize: Float?,
    var legumesAllocatedVegetables: Float?,
    var vegetablesVariationsScore: Float?,
    var vegetablesCruciferous: Float?,
    var vegetablesTuberAndBulb: Float?,
    var vegetablesOther: Float?,
    var legumes: Float?,
    var vegetablesGreen: Float?,
    var vegetablesRedAndOrange: Float?,

    // Fruits
    var fruitHeifaScoreMale: Float?,
    var fruitHeifaScoreFemale: Float?,
    var fruitServeSize: Float?,
    var fruitVariationsScore: Float?,
    var fruitPome: Float?,
    var fruitTropicalAndSubtropical: Float?,
    var fruitBerry: Float?,
    var fruitStone: Float?,
    var fruitCitrus: Float?,
    var fruitOther: Float?,

    // Grains and cereals
    var grainsAndCerealsHeifaScoreMale: Float?,
    var grainsAndCerealsHeifaScoreFemale: Float?,
    var grainsAndCerealsServeSize: Float?,
    var grainsAndCerealsNonWholeGrains: Float?,

    // Whole grains
    var wholeGrainsHeifaScoreMale: Float?,
    var wholeGrainsHeifaScoreFemale: Float?,
    var wholeGrainsServeSize: Float?,

    // Meat and alternatives
    var meatAndAlternativesHeifaScoreMale: Float?,
    var meatAndAlternativesHeifaScoreFemale: Float?,
    var meatAndAlternativesWithLegumesAllocatedServeSize: Float?,
    var legumesAllocatedMeatAndAlternatives: Float?,

    // Dairy and alternatives
    var dairyAndAlternativesHeifaScoreMale: Float?,
    var dairyAndAlternativesHeifaScoreFemale: Float?,
    var dairyAndAlternativesServeSize: Float?,

    // Sodium
    var sodiumHeifaScoreMale: Float?,
    var sodiumHeifaScoreFemale: Float?,
    var sodiumMgMilligrams: Float?,

    // Alcohol
    var alcoholHeifaScoreMale: Float?,
    var alcoholHeifaScoreFemale: Float?,
    var alcoholStandardDrinks: Float?,

    // Water
    var waterHeifaScoreMale: Float?,
    var waterHeifaScoreFemale: Float?,
    var water: Float?,
    var waterTotalML: Float?,
    var beverageTotalML: Float?,

    // Sugar
    var sugarHeifaScoreMale: Float?,
    var sugarHeifaScoreFemale: Float?,
    var sugar: Float?,

    // Saturated Fat
    var saturatedFatHeifaScoreMale: Float?,
    var saturatedFatHeifaScoreFemale: Float?,
    var saturatedFat: Float?,

    // Unsaturated Fat
    var unsaturatedFatHeifaScoreMale: Float?,
    var unsaturatedFatHeifaScoreFemale: Float?,
    var unsaturatedFatServeSize: Float?
)


